### ISSUE TITLE
Declaração desnecessária

### ISSUE THREAD

**Issue by ghost** [IgorWL/discordbot#1]
https://github.com/IgorWL/discordbot/blob/9b258f98330a0700546dbf82c03a97c7c7ccb58a/index.js#L4

**Comment by IgorWL** [comment]
> https://github.com/IgorWL/discordbot/blob/9b258f98330a0700546dbf82c03a97c7c7ccb58a/index.js#L4
thanks :)

**Comment by ghost** [comment]
:3
